---
- name: EddieS_Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    version: ""
    path: "/mswg/release/sx_mlnx_os/"

    cpu: "X86_64"   # X86_64 | PC_M460EX
    user: eddies
    password: eddies11
    remote_ip: 10.7.157.118
    reset: no
    command: "show clock"
    local_user: "{{ lookup('env', 'USER') }}"
    subset: version
  remote_user: admin
  roles:
    - { role: onyx_image_fetch_install , tags: ['image-fetch-install'] }
    - { role: onyx_basic_lab_mgmt_config , tags: ['onyx_basic_lab_mgmt_config'] }
    - { role: onyx_boot_next_save_config_reload , tags: ['boot_next'] }
    - { role: facts , tags: ['onyx_facts'] }
    - { role: bgp , tags: ['bgp'] }
    - { role: reset_factory, tags: ['wipe']}
    - { role: onyx_command, tags: ['onyx_command']}
    - { role: onyx_push_my_key, tags: ['push_key']}
    - { role: onyx_save_config, tags: ['save_config']}
