---
- name: mlag
  hosts: MLAG
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    reset: factory
    pause_after_reset: 4
    pause_value: 4
    wait_for_protocol_port: 22
  roles:
    - { role: onyx_reset_factory, tags: ['reset_factory'] }
    - { role: pause, tags: ['pause_']}
  #  - { role: wait_for_me, tags: ['wait_for_me']}
    - { role: onyx_fix_configuration_wizard, tags: ['fix_config_wizard']}
    - { role: onyx_basic_lab_mgmt_config, tags: ['mgmt_config']}
    - { role: mlag, tags: ['role_mlag'] }
