---
#- gather_facts: no
#- vars:
#   local_user: "{{ lookup('env', 'USER') }}"
# tasks:
#- name: print local user
#  debug: msg="{{ lookup('env','HOME') }} is an environment variable"

- name: create_find_key
  shell: ls {{local_user}}/.ssh/id_rsa.pub || /usr/bin/ssh-keygen -b 2048 -t rsa -f /{{local_user}}/.ssh/id_rsa.pub -q -N ""
  delegate_to: localhost
  ignore_errors: yes
  run_once: yes

- name: get_key_value
  shell: cat /{{local_user}}/.ssh/id_rsa.pub
  delegate_to: localhost
  register: public_key
  run_once: yes

#- name: print public key
#  debug: msg="{{ public_key.stdout }} is an environment variable"
#  delegate_to: localhost
#  run_once: yes
 
- name: configure_key
  onyx_config:
    commands: ssh client user admin authorized-key sshv2 "{{ public_key.stdout }}"
  register: config
   
- name: print switch answer
  debug: msg "{{ config.updates }}
  
