---
- name: get_facts_from_device
  onyx_facts:
    gather_subset: version
  when: cpu == "X86_64"

- name: image fetch
  onyx_command:
     commands: image fetch scp://{{ user }}:{{ password }}@{{remote_ip }}:{{ path }}/sx_mlnx_os-{{ version }}/{{ cpu  }}/image-{{ cpu }}-{{ version }}.img

- name: image install
  onyx_command:
     commands: image install image-{{ cpu }}-{{ version }}.img
  when:  (ansible_net_version['Product release'] is defined and ansible_net_version['Product release'] != version) or (cpu == "PPC_M460EX")
