---
- name: get_facts_from_device
  onyx_facts:
    gather_subset: version

- name: image fetch
  onyx_command:
     commands: image fetch scp://{{ user }}:{{ password }}@{{remote_ip }}:{{ path }}/sx_mlnx_os-{{ version }}/{{ cpu  }}/image-{{ cpu }}-{{ version }}.img

- name: image install
  onyx_command:
     commands: image install image-{{ cpu }}-{{ version }}.img
  when:  ansible_net_version['Product release']  != version 
